--
-- Добавляем таблицу Сотрудник
--
CREATE TABLE employee
(
    id            int8 generated by default as identity,
    date_of_birth timestamp,
    email         varchar(255),
    login         varchar(255),
    name          varchar(255),
    password      varchar(255),
    role          varchar(255),
    status        varchar(255),
    department_id int8,
    primary key (id)
);

COMMENT ON TABLE employee IS 'Таблица сотрудников';
COMMENT ON COLUMN employee.id IS 'Идентификатор записи';
COMMENT ON COLUMN employee.name IS 'Имя сотрудника';
COMMENT ON COLUMN employee.date_of_birth IS 'День рождения сотрудника';
COMMENT ON COLUMN employee.email IS 'Электронная почта сотрудника';
COMMENT ON COLUMN employee.department_id IS 'Идентификатор отдела, в котором работает сотрудник';
COMMENT ON COLUMN employee.login IS 'Логин сотрудника';
COMMENT ON COLUMN employee.password IS 'Пароль для входа сотрудника в систему';
COMMENT ON COLUMN employee.role IS 'Роль сотрудника';
COMMENT ON COLUMN employee.status IS 'Статус сотрудника';

--
-- Добавляем таблицу Отдел
--
CREATE TABLE department
(
    id              int8 generated by default as identity,
    department_name varchar(255),
    primary key (id)
);

COMMENT ON TABLE department IS 'Таблица подразделений предприятия';
COMMENT ON COLUMN department.id IS 'Идентификатор записи';
COMMENT ON COLUMN department.department_name IS 'Наименование отдела';

--
-- Добавляем таблицу Собрание
--
CREATE TABLE meeting
(
    id                      int8 generated by default as identity,
    date_spending           timestamp,
    topic                   varchar(255),
    organized_department_id int8,
    organized_employee_id   int8 not null,
    report_id               int8,
    primary key (id)
);

COMMENT ON TABLE meeting IS 'Таблица собраний';
COMMENT ON COLUMN meeting.id IS 'Идентификатор записи';
COMMENT ON COLUMN meeting.date_spending IS 'Дата проведения собрания';
COMMENT ON COLUMN meeting.topic IS 'Название собрания';
COMMENT ON COLUMN meeting.organized_department_id IS 'Идентификатор отдела организатора собрания';
COMMENT ON COLUMN meeting.organized_employee_id IS 'Идентификатор сотрудника организатора собрания';
COMMENT ON COLUMN meeting.report_id IS 'Идентификатор доклада для собрания';

--
-- Добавляем таблицу Участников собраний
--
CREATE TABLE participants
(
    meeting_id  int8 not null,
    employee_id int8 not null
);

COMMENT ON TABLE participants IS 'Таблица участников собраний';
COMMENT ON COLUMN participants.meeting_id IS 'Идентификатор собрания';
COMMENT ON COLUMN participants.employee_id IS 'Идентификатор сотрудника';

--
-- Добавляем таблицу Доклад
--
CREATE TABLE report
(
    id           int8 generated by default as identity,
    content      TEXT,
    date_created timestamp,
    title        varchar(255),
    author_id    int8,
    primary key (id)
);

COMMENT ON TABLE report IS 'Таблица докладов';
COMMENT ON COLUMN report.id IS 'Идентификатор доклада';
COMMENT ON COLUMN report.content IS 'Содержание доклада';
COMMENT ON COLUMN report.date_created IS 'Дата создания доклада';
COMMENT ON COLUMN report.title IS 'Название доклада';
COMMENT ON COLUMN report.author_id IS 'Идентификатор автора доклада';

alter table if exists employee
    add constraint employee_department_fk foreign key (department_id) references department;
alter table if exists meeting
    add constraint meeting_department_fk foreign key (organized_department_id) references department;
alter table if exists meeting
    add constraint meeting_employee_fk foreign key (organized_employee_id) references employee;
alter table if exists meeting
    add constraint meeting_report_fk foreign key (report_id) references report;
alter table if exists participants
    add constraint participants_employee_fk foreign key (employee_id) references employee;
alter table if exists participants
    add constraint participants_meeting_fk foreign key (meeting_id) references meeting;
alter table if exists report
    add constraint report_employee_fk foreign key (author_id) references employee;